config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :orders, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'order/create'

  #
  # get 'sessions/new'
  #
  # get    '/cart',   to: 'sessions#new'
  # post   '/cart',   to: 'sessions#create'
  # delete '/empty',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :comments
  resources :products
  resource :cart
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :taggings
    has_many :products, through: :taggings
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_default_values

  private
    def set_default_values
      if self[:status].nil?
        self[:status] = "PENDING"
      end
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  def find_product(pid)
    if self.product.exist(pid)
      product.id
    else
      errors.add(:product, "can not find such product")
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :taggings
    has_many :categories, through: :taggings
    has_many :order_items
    has_many :comments
    before_save :set_default

    def rate(rating)
        self[:total_rating] += rating
        self[:times_rated] +=1
        set_rating
    end

    private
    def set_rating
        self[:rating] = self[:total_rating] / self[:times_rated]
    end

    def set_default
        if self[:rating].nil? && self[:times_rated].nil? && self[:total_rating].nil?
            self[:rating] = 0
            self[:times_rated] = 0
            self[:total_rating] = 0
        else
            set_rating
        end
    end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  # helper_method :get_comment


  def current_order
    @cart = session[:cart]
    @cart ||= {}
    session[:cart] = @cart
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order
    @order_item = OrderItem.new
    @products = Product.all
  end

  def update
    current_order.update
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper_method :get_comment

  def create
    # debugger
    if Comment.new(comment_params)
      puts "got new params"
      com = Comment.new(comment_params)
      com.save
      p = Product.find(comment_params[:product_id])
      p.times_rated += 1
      p.total_rating += comment_params[:rating].to_i
      p.save
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:product_id, :user_id, :text, :rating)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    puts "CReate order"
    newo = Order.create!
    newo.total = 0
    newo.subtotal = 0
    newo.name = params[:name]
    newo.address = params[:address]
    session[:cart].each do |product_id, item|
      uprice = Product.find(product_id).price
      tprice = uprice * item['quantity'].to_i
      ii = OrderItem.new(order: newo, 'product_id': product_id, 'quantity': item['quantity'],
                         'unit_price': uprice, 'total_price': tprice)
      newo.total += 1
      newo[:subtotal] += tprice
      ii.save
    end
    if newo.save!
      session.delete(:cart)
    end

  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    puts "add to cart, finding product with id "
    item = order_item_params
    # debugger
    if session[:cart][item['product_id']]
      session[:cart][item['product_id']]['quantity'] = session[:cart][item['product_id']]['quantity'].to_i +
          item['quantity'].to_i
    else
      session[:cart][item['product_id']] = item
    end

  end

  def update
    puts "UPDATE cart id quantity "

    if session[:cart][params[:id]]
      session[:cart][params[:id]]['quantity'] = params[:quantity]
    end
    redirect_to "/cart"
  end

  def destroy
    puts "remove item from cart"
    if session[:cart][params[:id]]
      session[:cart].delete(params[:id])
    end
    redirect_to "/cart"
  end

private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @cart = session[:cart]
    @cart ||= Array.new
    
    @categories = Category.all
    @products = Product.all
    @order_item = OrderItem.new
  end

  def show
    @category = Category.all
    @product = Product.find(params[:id])
    @order_item = OrderItem.new
    @comments = Comment.all
    @comment = Comment.new
    # debugger
  end
  #
  # def rate
  #   product = Product.find(params[:id])
  #   product.rate(params[:rating])
  #   product.save
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_comment(pid, uid)
    Comment.where(product_id:  pid, user_id: uid);
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_tag(order_item_path(product.id), method: :put) do %>
        <h4 class="text-right">Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= number_field_tag 'quantity', quantity, class: "form-control", min: 1 %>
            <%= hidden_field_tag 'product_id', value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= submit_tag "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item_path(product.id), { data: { confirm: "Are you sure you wish to delete the product '#{product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
<!--        <h4 class="text-right">Total Price: <span style="color: green"><%#= number_to_currency order_item.total_price %></span></h4>-->
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |product_id, order_item| %>
    <%= render 'carts/cart_row', product: @products.find(product_id), quantity: order_item['quantity'], show_total: true %>
  <% end %>
<% end %>
<h2>Checkout</h2>
<%= form_tag("order/create", remote: true) do %>
  <%= label_tag "Name" %>
  <%= text_field_tag "name", nil, placeholder: 'Enter your name', required: true%><br/>

  <%= label_tag "Address" %>
  <%= text_field_tag "address", nil, placeholder: 'Enter your address',required: true %><br/>

  <%= submit_tag "Submit Order", class: "btn btn-primary" %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/comments/create.js.erb
alert('Thanking for your review!')
location.reload();

app/views/order/create.js.erb
alert("Order submitted, redirectting to homepage")
window.location.href = "/"

app/views/order_items/create.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
alert("added product")

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
alert("updated cart")

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= link_to product.name, product %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>


<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @categories.each do |cate| %>
      <h3><%= cate.name%> (<%=cate.products.count%>)</h3>
      <ul>
        <% cate.products.order(:id).each do |product|%>
          <%= render "product_row", product: product, order_item: @order_item %>
        <% end %>
      </ul>
    <% end %>

  <% if false %>
    <% @products.order(:id).limit(10).each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  <%end%>
  </div>
</div>

app/views/products/show.html.erb
<h1 class="text-center">Book: <%= @product.name %></h1>

<h2>Author: <%=@product.author %></h2>
<h2>Description: </h2>
<p><%= @product.description %></p>
<div id="productRating" data-rating="<%= @product.rating %>"></div> ( Rated <%=@product.times_rated %> times)

<%= form_for @order_item, remote: true do |f| %>
  <h4 class="text-left">Unit Price: <span style="color: green"><%= number_to_currency @product.price %></span></h4>
  <a>Add to cart:</a>
  <div class="input-group" style="width: 300px">
    <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
    <div class="input-group-btn">
      <%= f.hidden_field :product_id, value: @product.id %>
      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% if user_signed_in? %>
    <%= form_for (@comment), remote: true do |ff| %>
      <div style="border: black; border-width: 2px">
        Your review and rating:<br/>
        <div id="rater"></div><br/>
        <%= ff.text_area('text', size: "5x5", required: true) %><br/>
        <%= ff.hidden_field :product_id, value: @product.id %>
        <%= ff.hidden_field :user_id, value: current_user.id %>
        <%#= ff.hidden_field 'myrating', value: 0 %>
        <input type="hidden" id="comment_rating" name="comment[rating]"/>
        <%#= ff.submit 'Submit review', class: "btn btn-primary"%>
        <input type="submit" id="btnSubmit" value="Submit review">
      </div>
    <% end %>

<% else %>
  <a>Login to leave a comment and rate!</a>
<% end %>
<!--  Comment section-->
<div style="border-width: 2px; border: black; width: 600px">
  <% if !@comments.where(product_id: @product.id).empty? %>
    <h2>People's review on this product:</h2><hr/>
    <% @comments.where(product_id: @product.id).each do |comment| %>
      <div style="border: black; border-width: 3px; margin-left: 20px">
        <h3><%=comment.user.email %> said:</h3>
        <p><%=comment.text %></p>
        <hr/>
      </div>
    <% end %>
  <% end %>
</div>

<script>
    // alert("lolol");
    console.log("hello")
    //product's ratign
    var pRating = raterJs( {
        element:document.querySelector("#productRating"),
        rateCallback:function rateCallback(rating, done) {
            pRating.setRating(rating);
            done();
        },
        showToolTip: false,
        readOnly: true
    });
    if ($('.user-status').hasClass('signed-in')) {

    }
    pRating.setRating($('productRating').data('rating'));
    //user's rating
    var myRating = raterJs( {
        element:document.querySelector("#rater"),
        rateCallback:function rateCallback(rating, done) {
            myRating.setRating(rating);
            document.getElementById('comment_rating').value = rating;
            done();
        },
        showToolTip: false
        <% if user_signed_in? %>
        <% if !@comments.where(product_id: @product.id, user_id: current_user.id).first.nil? %>
        ,readOnly: true
        <% end %>
        <% end %>
    });

    //disable comments if user commented
    <% if user_signed_in? %>
    console.log("user signed in ")
    <% if !@comments.where(product_id: @product.id, user_id: current_user.id).first.nil? %>

    //user has commented on this product, set value and disable the form
    <% cc = @comments.where(product_id: @product.id, user_id: current_user.id).first %>
    myRating.setRating(<%= cc.rating %>)
    document.getElementById('comment_text').value = '<%= cc.text %>';
    document.getElementById('comment_text').disabled = true;
    document.getElementById('btnSubmit').style.visibility = 'hidden';
    <% end %>
    <% end %>
</script>